version: '3.8'
services:
  db:
    image: postgres
    container_name: ffdDB
    restart: always
    environment:
      POSTGRES_DB: ffd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    networks:
      - ffd-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ffdServer
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ffd
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      db:
        condition: service_started
    networks:
      - ffd-net

networks:
  ffd-net:
    driver: bridge

volumes:
  db-data:
    driver: local
  ffd_images:
    driver: local