server:
  port: 8079

spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8080
          predicates:
            - Path=/user/**
        - id: item
          uri: http://localhost:8081
          predicates:
            - Path=/ms2/**
        - id: order
          uri: http://localhost:8082
          predicates:
            - Path=/ms3/**