server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: http://localhost:8081
          predicates:
            - Path=/admin/items/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/admin/orders/**
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/admin/users/**
